export enum Modes {

    TOP_LEFT_TO_RIGHT = 0,
    TOP_RIGHT_TO_LEFT = 1,

    BOTTOM_LEFT_TO_RIGHT = 2,
    BOTTOM_RIGHT_TO_LEFT = 3,

    LEFT_TOP_TO_BOTTOM = 4,
    LEFT_BOTTOM_TO_TOP = 5,

    RIGHT_TOP_TO_BOTTOM = 6,
    RIGHT_BOTTOM_TO_TOP = 7,

    RAND = 8,
    
}